version: 2
jobs:
  build:
    working_directory: ~/shiro
    docker:
      - image: marc3842h/shiro:ci
    branches:
      only:
        - staging
        - trying
        - master
    steps:
      - checkout
      - run:
          name: Generate CMake file
          command: |
            cmake .
      - run:
          name: Build
          command: |
            make -j2
      - store_artifacts:
          path: ~/shiro/bin/shiro
          destination: shiro
      - deploy:
          name: Deploy to development server
          command: |
            curl -X POST                                                                      \
                 -H "User-Agent: CircleCI $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"  \
                 -F "token=$SHIRO_DEPLOY_TOKEN"                                               \
                 -F "commit=$CIRCLE_SHA1"                                                     \
                 -F "file=@$HOME/shiro/bin/shiro"                                             \
                 https://c.shiro.host/api/ci_trigger
