# Bancho configuration file for Shiro

[server]
host = "127.0.0.1"
port = 8080
# Amount of concurrent connections the server accepts.
# Set this higher if you have more players, however also results in more RAM being used.
concurrency = 64

[permissions]
# Allow users with no roles / permissions to have supporer in-game?
default_supporter = true

[api]
key = "osu!Bancho token"

[motd]
alert = "Welcome to Shiro"
# The image needs to be on the host "i.ppy.sh"
title_image = "https://i.ppy.sh/motd.png"
title_url = "https://shiro.host"

[integrations]
sentry = true
